// 战斗系统 GameplayTag 声明（AutoChessCore）。
// 约定：热路径使用 FNativeGameplayTag，不做字符串比较；命名规范见 TechDocs/附录 B。
#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace BattleTags
{
    // ---------- 事件钩子 Hook.* ----------
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BattleStart);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BattleEnd);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Spawn);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Death);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Revive);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BeforeAttack);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_AfterAttack);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Hit);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Crit);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Kill);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_AssistKill);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BeforeSkillCast);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_SkillCast);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_SkillInterrupted);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_AllyAttack);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_AllySkillCast);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_EnemySkillCast);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BeforeTakeDamage);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BeforeDealDamage);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_TakeDamage);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_DamageDealt);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_ShieldBroken);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_ShieldGain);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Heal);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_Overheal);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_StateAdded);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_StateRemoved);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_BeforeStateApply);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_StateTick);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_FocusFull);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_FocusChanged);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_ChargeChanged);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_MentalChanged);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_MentalBreak);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_PreemptiveTrigger);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_PostEffectTrigger);
    // 阶段 4（§7 阶段 4）：`Hook_TimelineModified` **已删除** —— 它从来没有派发者。
    // 旧 `FTimelineSystem` 只在 `ExtendPreemptive` / `AdvancePostEffect` / `RefreshPreemptive`
    // 三个改写 API 里会派发它，而那三个 API 在全仓**没有任何调用者**（阶段 3.2b 已 grep 核实），
    // 时间轴改写整体不实现，因此这条钩子连"曾经被派发过"都没有过。
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_UnitMoved);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hook_TargetChanged);

    // ---------- 单位身份 Unit.* ----------
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Warrior);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Tank);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Assassin);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Shooter);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Technician);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Class_Support);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Camp_Mechanic);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Camp_Jianghu);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Kind_Operator);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Kind_Enemy);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Kind_Summon);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tag_Ranged);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tag_Melee);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tag_Elite);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tag_Boss);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tag_Marked);

    // ---------- 异常状态 State.* ----------
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Bleed);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wound);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Poison);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Burn);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Corrosion);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Freeze);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Shield);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PersistentShield);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_StaticDisorder);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Silence);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Taunt);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Charge);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stun);

    // ---------- 伤害类型 Damage.Type.* ----------
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Physical);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Technical);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_True);
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Mental);

    // ---------- 效果触发器 Effect.Trigger.* ----------
    //
    // 阶段 4（§7 阶段 4「`ACBattleTags.h` 的 `Effect_Trigger_*`」）：
    //   · `Effect_Trigger_Preemptive` —— **保留**。它不是残留：阶段 3.2b 起它是"抢攻"这件事的
    //     **唯一判据** —— `UACGE_Equip_Gold_FlowBlade_Preemptive` 把它写进 `GrantedTags`
    //     （`ACGE_ContentEffects.cpp`），表现层遍历单位 ASC 的活动 GE 时按它区分
    //     "抢攻"与"其他限时 GE"，`UBattleWorld::ApplyPreBattleConfiguration` 走的也是这条路。
    //     换句话说，§3.1 表里"删 5 个、从未被派发"的结论对另外两个成立，对这一条**已不成立**。
    //   · `Effect_Trigger_PostEffect` / `Effect_Trigger_Periodic` —— **已删除**：
    //     全仓 grep 只有声明与定义两处，没有任何 GE 授予它们、没有任何代码按它们查询
    //     （后发的判据是内核侧待触发表的 `FPendingTimelineFire`，周期的判据是 GE 的 `Period`，
    //      两者都不需要标签）。
    AUTOCHESSCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Trigger_Preemptive);
}
